name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: yohn-jp/.github/.github/workflows/typescript-cli-ci.yml@f9ac0b0ea6f50b815d2f2b6f4c97650d79b9b994
    with:
      working-directory: .
      node-version: "22"
