name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  ci:
    uses: yohn-jp/.github/.github/workflows/typescript-cli-ci.yml@49a11303f40de2663b61aa9ece0925d8acb381f8
    with:
      working-directory: .
      node-version: "22"
