name: PR governance

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  governance:
    uses: yohn-jp/.github/.github/workflows/pr-governance.yml@34846fadafb3f719b00ec7da6d78bcbcc4cfdc40
