name: Issue governance

on:
  issues:
    types: [opened, edited, reopened]

permissions:
  contents: read
  issues: write

jobs:
  governance:
    uses: yohn-jp/.github/.github/workflows/issue-governance.yml@f9ac0b0ea6f50b815d2f2b6f4c97650d79b9b994
